import java.awt.Graphics;
import java.awt.event.*;
import java.awt.*;
import java.applet.*;
import java.util.*;

@SuppressWarnings("unused")
class superTrain {

  private static Color baseColor = new Color(72, 72, 72);
  static protected int p1 = 100;
  static protected int p2 = 300;
  static protected int p3 = 150;
  static protected int p4 = 100;
  
  private static int adjust;
  static protected int adjustAdjust = (getAdjust()/2)-(getAdjust()/2); //messed with the numbers until it worked (yes I know this equals 0)
  
  static protected int frontX;
  static protected int backX;
  static protected int Y;
  
  public static Color black = new Color(0,0,0);
  public static Color white = new Color(255,255,255);
  
  
  
  
  
  
  

  public void buildCar(Graphics g) {
    functions.intro("Constructing train car with color: " + getBaseColor());

    Point first = new Point(p1, p2);
    Point second = new Point(p3, p4); //composition

    // drawRect displays in x1,y1,width,height
    g.setColor(getBaseColor());
    g.fillRect(first.getX()+getAdjust(), first.getY(), second.getX()+adjustAdjust, second.getY());
    g.setColor(black);
    g.drawRect(first.getX()+getAdjust(), first.getY(), second.getX()+adjustAdjust, second.getY());
    
    
    
    //Wheels
    frontX = (first.getX()+5)+getAdjust();
    backX = ((first.getX()+p3)-55)+getAdjust();
    Y = first.getY()+70;
    
    g.setColor(black);
    g.fillOval(frontX, Y, 50, 50);
    g.fillOval(backX, Y, 50, 50);
    
    g.setColor(white);
    g.drawOval(frontX, Y, 50, 50);
    g.drawOval(backX, Y, 50, 50);
    

  }
  
  
  
  
  
  
  
  
//Get and Set methods - This section was auto-generated by Eclipse IDE (indentation may be strange).
public static Color getBaseColor() {
	return baseColor;
}

public static void setBaseColor(Color baseColor) {
	superTrain.baseColor = baseColor;
}

public static int getAdjust() {
	return adjust;
}

public static void setAdjust(int adjust) {
	superTrain.adjust = adjust;
}

}//End of superTrain class